name: flutter_twilio_conversations
description: Integrate the Twilio Conversations SDK with your Flutter app using this Twilio Conversations Flutter plugin
version: 1.1.2+4
repository: https://github.com/Diversido/flutter_twilio_conversations
issue_tracker: https://github.com/Diversido/flutter_twilio_conversations/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
    
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_conversations
        pluginClass: TwilioConversationsPlugin
      ios:
        pluginClass: TwilioConversationsPlugin